enableAllRules = true

[rule.package-comments]
Disabled = true
[rule.unused-parameter]
Disabled = true
[rule.unused-receiver]
Disabled = true
[rule.exported]
Disabled = true
[rule.max-public-structs]
Disabled = true

[rule.line-length-limit]
arguments = [120]